# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import datetime
import os
import sys

from pybtex.plugin import register_plugin  # noqa
from pybtex.style.formatting.alpha import Style as AlphaStyle  # noqa
from pybtex.style.labels import BaseLabelStyle  # noqa

sys.path.insert(0, os.path.abspath("../src/"))

import lsapy

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "lsapy"
copyright = f"2025-{datetime.datetime.now().year}, Baptiste Hamon & contributors"
author = "Baptiste Hamon"

# The short X.Y version.
version = lsapy.__version__.split("-")[0]
# The full version, including alpha/beta/rc tags.
release = lsapy.__version__

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.coverage",
    "IPython.sphinxext.ipython_console_highlighting",
    "sphinx_autodoc_typehints",
    "sphinxcontrib.bibtex",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_mdinclude",
    "myst_nb",
    "sphinxext.rediraffe",
]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "logos/lsapy/branding.md"]


# Bibliography stuff (from xclim package)
# a simple label style which uses the bibtex keys for labels
class XCLabelStyle(BaseLabelStyle):
    def format_labels(self, sorted_entries):
        for entry in sorted_entries:
            yield entry.key


class XCStyle(AlphaStyle):
    default_label_style = XCLabelStyle


register_plugin("pybtex.style.formatting", "xcstyle", XCStyle)
bibtex_bibfiles = ["references.bib"]
bibtex_default_style = "xcstyle"
bibtex_reference_style = "author_year"

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_title = "LSAPy Documentation"
html_short_title = "LSAPy"
html_logo = "logos/lsapy/LSAPy_Logo_FullColour.svg"
html_favicon = "logos/lsapy/LSAPy_Icon.png"

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme further.
# For a list of options available for each theme, see the documentation.
html_theme_options = {
    "icon_links": [
        {"name": "GitHub", "url": "https://github.com/baptistehamon/lsapy", "icon": "fa-brands fa-github"},
    ],
    # header and footer options
    "header_links_before_dropdown": 6,
    "navbar_align": "left",
    "footer_start": ["copyright"],
    "footer_center": ["sphinx-version"],
    # secondary sidebar options
    "use_edit_page_button": True,
    # Pygments light and dark theme styles
    "pygments_light_style": "xcode",
    "pygments_dark_style": "lightbulb",
}
# use pydata_sphinx_theme's default
html_show_sourcelink = False

html_context = {
    "github_user": "baptistehamon",
    "github_repo": "lsapy",
    "github_version": "documentation",
    "doc_path": "docs",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Redirects for moved pages
rediraffe_redirects = {
    "getting_started/index": "getting-started/index",
    "api/utils.rst": "api/tutorial.rst",
}

intersphinx_mapping = {
    "geopandas": ("https://geopandas.org/en/stable/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
    "xarray": ("https://docs.xarray.dev/en/stable/", None),
}


def setup(app):
    app.add_css_file("style.css")
